version: '3.1'

services:
  app:
    container_name: springboot-phonebook
    image: 'springboot-postgresql'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgresqldb:
    image: 'postgres'
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=phonebook