spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/phonebook
    password: '123456'
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    show-sql: 'true'
management:
  endpoints:
    web:
      cors:
        allowed-methods: GET
        allowed-origins: '*'
        allowed-headers: '*'
