apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: phonebook
  labels:
    app: frontend
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        env: test
    spec:
      containers:
        - name: frontend
          image: localhost:3000/ui:v1.0.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app-config
              mountPath: /app/config
      volumes:
        - name: app-config
          configMap:
            name: app-config
            items:
              - key: backend-url
                path: .env